### ISSUE TITLE
Publish binaries as artifacts

### ISSUE THREAD

**Issue by koppor** [carlbeech/fast-duplicate-finder#7]
GitHub offers uploading of binaries to releaes. Releases are stored at https://github.com/carlbeech/fast-duplicate-finder/releases.

Details: step 7 at <https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository>

I would propose to DELETE all files in 

- https://github.com/carlbeech/fast-duplicate-finder/tree/master/Linux_Standalone_Executables
- https://github.com/carlbeech/fast-duplicate-finder/tree/master/Windows

using [git BFG](https://rtyley.github.io/bfg-repo-cleaner/)

This would

a) reduce the repository size
b) speed up cloning
c) convert this repo to a more usual one.

The drawback is that all cloners and forkers (currently IMHO only you and me) have to reset their `master` branch to the new one.

**Comment by carlbeech** [comment]
Created a release (first time I've done this :-)  ) - note, as I've not had time to set up my python environment, I've had to use the 0.4 binaries, so this still has the windows bug - as soon as I've been able to build the new binaries I'll publish as 0.5 in step with source code.
Can you check - if its working ok, and if so, I'll drop the binaries out of the source code repo.

Cheers

Carl.

**Comment by koppor** [comment]
The 0.5 does not have the timestamp issue. It does not cope well with files being multiple GB in size (refs #9), but should be OK with smaller files.

**Comment by carlbeech** [comment]
Moved binaries to 'release' and removed from source.
