### ISSUE TITLE
Save the output file each hour

### ISSUE THREAD

**Issue by koppor** [carlbeech/fast-duplicate-finder#8]
On a large set of files, the program runs for several days. To enable a faster rusme on a paused program, would it be possible to save the intermediate state each hour? Is it "just" calling `SaveDatabase()` each hour and to ensure that it is not executed in parallel (in case the job finishes after 60.0001 0minutes while afer 60.0000 minutes the database is saved).

**Comment by carlbeech** [comment]
Just committed 0.6 which does regular file writes - at this point every 20 files compared.
Unfortunately it isn't possible just to call savedatabase periodically - the logic of the program is to read all the files, then, sort the list based on file size, work out the potential duplicates, then calculate hashes on those files and finally write the output file.

0.6 performs all the above for every 20 files, so after 20 files are added to the data structure it sorts, locates generates hashes and saves.

Assuming this works correctly, it should be possible to parameterize this.

Note that the original versions grabbed a list of files, therefore it 'knew' how many files it had to deal with, and therefore it was possible to have a progress bar - as the whole thing is done on the file scan, then the progress bar doesn't really work any more - its cosmetic, but I'll think if there's a way to improve.

Let me know how this goes...

**Comment by carlbeech** [comment]
Output file is now (re)generated for each 100 files being hashed.
