### ISSUE TITLE
Do not completely crash at "MemoryError"

### ISSUE THREAD

**Issue by koppor** [carlbeech/fast-duplicate-finder#9]
```
Total files:5398432
 =======================================  Matching files 5398403Traceback (most recent call last):
  File "fdf_scanner.py", line 1189, in <module>

  File "fdf_scanner.py", line 456, in CalculateHashes

MemoryError
```

The line where the crash happens:

    FileDB[i][4] = hashlib.sha256(open(FileDB[i][1], 'rb').read()).hexdigest()

The tool ran for several days and no database written. Everything has to be done from the beginning.

**Comment by carlbeech** [comment]
Hmm - this sounds more like a memory issue with hashlib?
Assuming that you're using the save database parameter, then it should be possible to perform a save database every x rows... which should mean less time performing a redo...
As a thought, it may be useful to attempt to use md5hash rather than sha256 - sha256 is more accurate (i.e. less chance of having two files with the same hash), but needs more processing...
I've got some time this weekend to investigate.

**Comment by koppor** [comment]
For a "simple" duplication detection, md5 - or even crc32 - should be enough. The tool is IMHO not intended to be used in settings where attackers created files with the same md5sum - or even the same sha check sum.

I think, the issue is that the file is completely read into memory for hashing. Isn't it possible that a stream is opened? Google discovered https://stackoverflow.com/a/44873382/873282 (and a longer text at https://subscription.packtpub.com/book/networking_and_servers/9781783987467/1/ch01lvl1sec14/hashing-files-and-data-streams). A contributor even created a pyhton3 library with shorter code: https://stackoverflow.com/a/48738172/873282

```terminal
pip3 install py_essentials
```

```python
from py_essentials import hashing as hs
hash = hs.fileChecksum("path/to/the/file.txt", "sha256")
```

**Comment by carlbeech** [comment]
Currently examining a method where calculating hash by opening file if file is too large - will upload test version in the next few days (still having issues re-setting up development environment)
Cheers
Carl.

**Comment by carlbeech** [comment]
0.6 has an alteration (using the -m parameter) if a file is more than 250Mb it uses a different method to work out the file hash.

Let me know how this works for you.
